### ISSUE TITLE
Can we have SendAsync on the senders?

### ISSUE THREAD

**Issue by xied75** [emertechie/SyslogNet#1]
Best,

Dong

**Comment by dmitry-shechtman** [comment]
Something like [this](https://github.com/YallaDotNet/syslog/blob/portable/Core/Transport/IAsyncSyslogMessageSender.cs)?

**Comment by xied75** [comment]
@dmitry-shechtman link no longer works. Frankly this is raised "long" time ago. I don't remember the details any more. :) BTW why your fork does not have "issues"?

**Comment by dmitry-shechtman** [comment]
I only released the first alpha yesterday. Thanks for letting me know, both fixed.
