### ISSUE TITLE
To strong name or not

### ISSUE THREAD

**Issue by emertechie** [emertechie/SyslogNet#10]
Received a request to strong name the assembly so adding an issue for discussion.

I've always found strong naming pretty painful myself, and I know it leads to a lot of [debate](https://github.com/octokit/octokit.net/issues/405). See [this](https://github.com/reactiveui/ReactiveUI/issues/43#issuecomment-37471892) comment and Microsoft's own recommendations [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md#1-microsoft-strong-names-their-assemblies-should-i) also.

So I'd naturally lean against it but if there's a genuine need, and someone is willing to do a pull request and merge it (cough, cough @grubman  :)  ) then fine by me.

**Comment by dmitry-shechtman** [comment]
Please do.

If you're _really_ opposed to it, you may release the signed package separately as `SyslogNet.Client.Signed`, in the worst of NuGet tradition :)

Let me know what you think, and whether you want me to do the PR.

**Comment by grubman** [comment]
I have no problem to merge and check it. I have a fairly busy week, so I'll find some time to read the links and decide how to release it only next week :)

**Comment by dmitry-shechtman** [comment]
I fail to see any problem with releasing just the strongly named one, given that the private key used for signing it is public.

**Comment by dmitry-shechtman** [comment]
#11

**Comment by grubman** [comment]
a lot of time have passed, and no PR was presented. closing it...
