### ISSUE TITLE
Portable client

### ISSUE THREAD

**Issue by dmitry-shechtman** [emertechie/SyslogNet#11]
I believe I just completed a PCL port of SyslogNet:

https://github.com/YallaDotNet/SyslogNet/tree/portable

I intend on releasing it separately. Before I do, may I suggest that we keep the two as compatible as possible by splitting them into the following packages:
1. **`SyslogNet.Client.Core`** : `SyslogMessage` and its dependencies + `SyslogTransportException`
   1. signed .NET 4 portable
2. **`SyslogNet.Client.Text`** : `ASCIIEncoding` and its dependencies
   1. signed .NET 4.5 portable
3. **`SyslogNet.Client.Serialization`** : `ISyslogMessageSerializer` and its implementations
   1. signed .NET 4 dependent on `SyslogNet.Client.Core`
   2. signed .NET 4.5 portable dependent on `SyslogNet.Client.Core` and `SyslogNet.Client.Text`
4. **`SyslogNet.Client`** : `ISyslogMessageSender` and its implementations
   1. dependent on `SyslogNet.Client.Serialization`, signing and platform are entirely up to you
5. **`Portable.SyslogNet.Client`** : `ISyslogMessageAsyncSender` and its implementations by yours truly
   1. dependent on `SyslogNet.Client.Serialization`
- I suggest that `CommunicationsException` be removed and (non-serializable) `SyslogTransportException` be used in its stead.

If these are acceptable, I am ready for merge.

**Edit:** No need to change the target in the desktop client, list updated accordingly.

**Comment by grubman** [comment]
it's been a while! sorry for the delay. 
It seems like a good change, and correct me if I'm wrong It will solve the strong naming issue as well, wont it?

**Comment by austinheap** [comment]
Any update on this? Would be great to get macOS support. Thank you both for the great work!

**Comment by grubman** [comment]
Try using https://github.com/YallaDotNet/syslog/tree/portable for MacOS.
It does not stated as supported, but you can try.

**Comment by grubman** [comment]
a lot of time have passed, and no PR was presented. closing it...
