### ISSUE TITLE
The structured Data Elements are optionnal

### ISSUE THREAD

**Issue by OPSnake** [emertechie/SyslogNet#14]
The structured Data Elements are optionnal in [RFC5424](https://tools.ietf.org/html/rfc5424#section-6).
Replace the empty structured data elements by NILValue in message.

This code generate invalide syslog message :
`var process = Process.GetCurrentProcess();`
`SyslogMessage messageKO = new SyslogMessage(`
`DateTime.Now,`
`Facility.UserLevelMessages,`
`Severity.Informational,`
`process.MachineName,`
`process.ProcessName,`
`process.Id.ToString(),`
`null,`
`"Bad log message");`

**Comment by grubman** [comment]
can you please fix it? I'll merge it

**Comment by bruno-garcia** [comment]
This PR solved this issue: https://github.com/emertechie/SyslogNet/pull/12

**Comment by grubman** [comment]
still waiting for @bruno-garcia to fix his PR (#12). if I'll find some time I'll do it myself.

**Comment by grubman** [comment]
closing issue after merging pr #12
