### ISSUE TITLE
Problem in Chinese environment 

### ISSUE THREAD

**Issue by stevencjhsiao** [emertechie/SyslogNet#16]
There are two issue found when use SyslogNet in Chinese Windows operating system.
1. message.DateTimeOffset.Value.Tostring("MMM ") get the Chinese month string in SyslogRfc3164MessageSerializer.cs
   Chinese month string will show in the message header, that cause syslog server consider the syslog header as message text.
   ie. 
   八月 27 22:45:23 HOSTNAME ........(Wrong)
   Aug 27 22:45:23 HOSTNAME ......(Correct)
2. Not support Chinese character in message.

Here is the fix in SyslogRfc3164MessageSerializer.cs
1. Add en-US CultureInfo when get the month string.
2. Change the encoding from ASCII to UTF8. 

```
namespace SyslogNet.Client.Serialization
{
    public class SyslogRfc3164MessageSerializer : SyslogMessageSerializerBase, ISyslogMessageSerializer
    {
        public void Serialize(SyslogMessage message, Stream stream)
        {
            var priorityValue = CalculatePriorityValue(message.Facility, message.Severity);

            string timestamp = null;
            if (message.DateTimeOffset.HasValue)
            {
                var dt = message.DateTimeOffset.Value;
                var day = dt.Day < 10 ? " " + dt.Day : dt.Day.ToString(); // Yes, this is stupid but it's in the spec
                timestamp = String.Concat(dt.ToString("MMM ", CultureInfo.CreateSpecificCulture("en-US")), day, dt.ToString(" HH:mm:ss"));
            }

            var headerBuilder = new StringBuilder();
            headerBuilder.Append("<").Append(priorityValue).Append(">");
            headerBuilder.Append(timestamp).Append(" ");
            headerBuilder.Append(message.HostName).Append(" ");
            headerBuilder.Append(message.AppName.IfNotNullOrWhitespace(x => x.EnsureMaxLength(32) + ":"));
            headerBuilder.Append(message.Message ?? "");

            //byte[] asciiBytes = Encoding.ASCII.GetBytes(headerBuilder.ToString());
            byte[] asciiBytes = Encoding.UTF8.GetBytes(headerBuilder.ToString());
            stream.Write(asciiBytes, 0, asciiBytes.Length);
        }
    }
}
```

**Comment by grubman** [comment]
please create a pull request

**Comment by stevencjhsiao** [comment]
I seem have no permission to create a branch for this pull request.

**Comment by grubman** [comment]
I'm sorry for the confusion, after checking [RFC 3164](https://www.ietf.org/rfc/rfc3164.txt)

> 4.1.2 HEADER Part of a syslog Packet
> 
>    The HEADER part contains a timestamp and an indication of the
>    hostname or IP address of the device.  The HEADER part of the syslog
>    packet MUST contain visible (printing) characters.  The code set used
>    MUST also be seven-bit ASCII in an eight-bit field like that used in
>    the PRI part.  In this code set, the only allowable characters are
>    the ABNF VCHAR values (%d33-126) and spaces (SP value %d32).

You can see that in this case the RFC enforces ASCII encoding, and no UTF-8 is allowed.

**Comment by stevencjhsiao** [comment]
You are right HEADER part should be seven-bit ASCII. However, the headerBuilder append the Message part at last, message may contain Chinese 8-bit character.
