### ISSUE TITLE
SyslogEncryptedTcpSender no timeout on SslStream

### ISSUE THREAD

**Issue by grubman** [emertechie/SyslogNet#2]
In the constructor of `SyslogEncryptedTcpSender`  you initialize `sslStream` with `NetworkStream` from `tcpClient`. `NetworkStreams`'s default timeout is infinite so when you are calling

> sslStream.AuthenticateAsClient(hostname);

the operation will block if the server is not responding.

Specifically i'm using Kiwi Syslog. When it is configured to listen to regular Tcp packets (not encrypted) and my application uses your nuget to open an Encryoted Tcp connection on the same port - my application hangs.

**Comment by emertechie** [comment]
Hi @grubman. Thanks for the pull request. I'm not actively developing on .Net these days - would you be interested in becoming a maintainer of the repo, with publishing rights? Otherwise, I will get to this pull request eventually but it could take some time

**Comment by grubman** [comment]
It would be great, i'll be more then happy to do so.

**Comment by emertechie** [comment]
Great. I've added you as collaborator on the repo so you should have push rights. Can you send me your NuGet.org username so I can add you as an owner there?

**Comment by emertechie** [comment]
My email is <github username>@gmail.com
