### ISSUE TITLE
Should there be a "SafeMessageSender" wrapper that would wrap an underlying Transport?

### ISSUE THREAD

**Issue by rwkarg** [emertechie/SyslogNet#24]
This would handle the task of thread safety and reconnects.

For example, sending could be simply posting to a BufferBlock<SyslogMessage> which is consumed async from a single consumer, serializing access to the underlying transport but getting it off of the producing thread.
Options could be provided for retry counts, circuit breaker max failures (if the destination just can't be reached) and open time, etc.

This would be an opt-in wrapper. Could be included in the core package (would pull in a DataFlow dependency, though that is a System level package) or as a separate one.

**Comment by grubman** [comment]
It sounds like a custom implementation that a user of this library should implement himself according to his special needs.
