### ISSUE TITLE
Revert changes to 434510a

### ISSUE THREAD

**Issue by nE0sIghT** [emertechie/SyslogNet#6]
I see there is massive indentation changes and framework 4.6 dependency bumping.

Space indentation is against tradition of this project and my own code style (that's why one of my commits was "Formatting"). Code style was one of reasons i started using this project.
Framework 4.6 not working with old but supported versions of Windows and against my needs.

Please revert those changes.

**Comment by grubman** [comment]
Done, sorry for the inconvenience... you'll find the nuget in the next minutes

**Comment by grubman** [comment]
Hi, What do you say about adding a project with a 4.6 dependency and a different code style? I'll take care of aligning the features among both projects, and i'll release two nugets every time.

Additionally, @emertechie, what is your opinion on that?

**Comment by emertechie** [comment]
I've no strong opinion on the 4.6 dependency as I'm out of .Net land at the moment, so I'll leave that decision to yourself.

What are the proposed code style changes?

**Comment by grubman** [comment]
Just a different method of spacing/indentation, usage of regions and a different naming conventions

**Comment by emertechie** [comment]
If it's just tabs to spaces, I'm not too fussed.

If more involved, I'd just question the utility and would prefer to keep the current style consistent. Can you give an example of proposed naming convention changes?

**Comment by emertechie** [comment]
oh skipped over "regions'... I'd _really_ prefer no to use them. I think they are a big code smell. Basically [this](http://programmers.stackexchange.com/a/53114/188895)

**Comment by grubman** [comment]
I get the regions thing, I can do without it. I normally use them to group methods from the same base class.

regarding the naming conventions - I'll prefer 'processId' instead of 'procId' or 'messageId' instead of 'msgId'.

but by far, the most important thing to me is async/await code and c#6 syntax.

**Comment by emertechie** [comment]
Oh yea, absolutely. Sounds good to me

**Comment by dmitry-shechtman** [comment]
@grubman I believe you can use C# 6.0 in .NET 1.1 code :)

async only requires 4.5, and if you _must_ remain on 4.0, you could use `Microsoft.Bcl.Async` (although I believe that and C# 6.0 won't play nicely together on VS12).
